# retrieve the swarm tokens and populate a list of ips listening on
# the swarm port 2377
---
- name: retrieve swarm manager token
  shell: docker swarm join-token -q manager
  register: swarm_manager_token

- name: retrieve swarm worker token
  shell: docker swarm join-token -q worker
  register: swarm_worker_token

- name: populate list of manager ips
  add_host:
    hostname: "{{ hostvars[item].ansible_eth1.ipv4.address }}"
    groups: swarm_manager_ips
  with_items: "{{ ansible_play_hosts | default(play_hosts) }}"